### ISSUE TITLE
Introduce solution first

### ISSUE THREAD

**Issue by MrValdez** [maegaudia/Project-Proposal#1]
The solution is the first thing that will be read and can give the reader context on your project. Even a summary is enough.

**Comment by maegaudia** [comment]
An Abstract will be added as an introduction to the proposal:

Abstract
Smoking is a dangerous and expensive habit, not only to the smoker, but to the people surrounding him as well. Despite the efforts of the government and the various health organizations of the different countries to control this, there is still a significant percentage of smokers all over the world.The researcher proposes to use the aid of technology and create an application that will aid the users in quitting smoking for good. This app will keep track of the progress of the user, and has features that will serve as further incentives to make the user want to quit smoking. Some of the features include a calculator for money saved, health risks from smoking and benefits from quitting, a social networking feature, and various achievements in a form of badges in relation to their progress.

**Comment by MrValdez** [comment]
Looks good.
