### ISSUE TITLE
Look up gamification

### ISSUE THREAD

**Issue by MrValdez** [maegaudia/Project-Proposal#2]
I think your proposal is suited to gamification.

https://www.youtube.com/results?search_query=gamification+extra+credits

Tell me why or why not.

**Comment by maegaudia** [comment]
I agree that it is indeed suited for gamification.

The achievement feature is similar to those that one gets in games, just like in Steam or the PlayStation games. With the social networking feature (the buddy system) where others can see the user's achievements in the form of badges in the user's profile, it will make other users feel competitive and put in more effort in increasing their own badges. This would make users more likely to improve their quitting process, which is the main reason for this application in the first place.

**Comment by maegaudia** [comment]
Gamification will be implemented in this application. Further study will be made in order to find other aspects of the application or add more features which could use the idea of gamification.
